In [1]:
import json
import scipy.sparse as sp
import numpy as np
from functools import partial
import matplotlib.pyplot as plt
from datetime import datetime as dt
import tensorflow as tf

In [36]:
vec = np.random.random((3,))
vec /= np.linalg.norm(vec)
vec

array([0.62098624, 0.51456308, 0.5912706 ])

In [37]:
x = np.array([1, 0, 0])
k = np.cross(vec, x)
k /= np.linalg.norm(k)
K = np.cross(np.eye(3), k)
theta = np.arccos(vec[0] / np.linalg.norm(vec))
R = np.eye(3) - np.sin(theta) * K + (1 - np.cos(theta)) * np.einsum("ij,jk->ik", K, K)
np.einsum("ij,j->i", R, x)

array([0.62098624, 0.51456308, 0.5912706 ])

In [29]:
np.einsum("i,i->", x, k)

0.0

In [31]:
K

array([[-0.        ,  0.6848132 ,  0.72871865],
       [-0.6848132 ,  0.        ,  0.        ],
       [-0.72871865,  0.        ,  0.        ]])

In [32]:
k

array([ 0.        ,  0.72871865, -0.6848132 ])